project:
  type: website
  output-dir: docs

website:
  title: "C4"
  navbar:
    logo: fig/CHORDS_icon_logo_nobackgorund.png
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



