---
title: "C4: CHORDS and CAFE Compuational Chorus Community of Practice"
---

# CHORDS

[Climate Health Outcomes Research and Data Systems](https://niehs.github.io/chords_landing/q)

# CAFE

[Climate Change and Health Research Coordinating Center](https://climatehealthcafe.org/)

# What are computational best-practices?

We want to support and promote reproducible and open-source computational methods for
the environmental health sciences. Best-practices include:

- Open Source
- Version Control
- Continuous Integration 
- Unit and Integration Testing
- Reproducible Pipelines

## Focus Areas

We are developing a governance plan which will include focus areas, but we envision
something along the lines of (1) Geospatial Methods (2) Health Analyses (3) Geophysics 
and (4) Computer Science

# Get Involed

We are in the process of developing a strategy for forming the community of practice
around best-practices for computational methods and applications in the environmental 
health sciences. We encourage anyone interested in this topic to provide their contact
information below, so you can be involved.

Please enter your email to subscribe to our newsletter.

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSev0TuYQaXTr-avUPXs99sbeTB5xuamQWB3_XO95N0klA23gA/viewform?embedded=true" width="640" height="784" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>